<?php
/**
 * AdEngagementCountsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zernio\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AdEngagementCountsTest Class Doc Comment
 *
 * @category    Class
 * @description The single &#x60;engagement&#x60; total split into the interactions behind it.  Note that &#x60;engagement&#x60; is not the sum of these: Meta&#39;s own &#x60;post_engagement&#x60; and &#x60;page_engagement&#x60; totals already contain the individual interactions, and all of them are counted into &#x60;engagement&#x60;. Use these fields when you need a specific interaction, and &#x60;engagement&#x60; only as the coarse total it has always been.  Meta-only; other platforms leave these at 0.
 * @package     Zernio
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AdEngagementCountsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AdEngagementCounts"
     */
    public function testAdEngagementCounts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "post_engagement"
     */
    public function testPropertyPostEngagement()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "page_engagement"
     */
    public function testPropertyPageEngagement()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reactions"
     */
    public function testPropertyReactions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shares"
     */
    public function testPropertyShares()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "saves"
     */
    public function testPropertySaves()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "page_likes"
     */
    public function testPropertyPageLikes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "video_views"
     */
    public function testPropertyVideoViews()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "link_clicks"
     */
    public function testPropertyLinkClicks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
