<?php
/**
 * AdFunnelCountsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zernio\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AdFunnelCountsTest Class Doc Comment
 *
 * @category    Class
 * @description Named conversion-funnel steps, resolved from the same data as &#x60;actions&#x60; so you never have to parse action-type strings yourself.  Meta reports one event under several action types at once (&#x60;offsite_conversion.fb_pixel_purchase&#x60;, &#x60;omni_purchase&#x60;, &#x60;purchase&#x60;, …). Each field below takes the FIRST family member present rather than summing them, which is what makes these counts safe to add up — summing the raw &#x60;actions&#x60; keys yourself double or triple counts. The same priority order backs &#x60;conversions&#x60;, so a purchase-optimised campaign reports the identical number in &#x60;conversions&#x60; and &#x60;funnel.purchases&#x60;.  Every field is 0 when that step never fired. Populated for Meta ads; other platforms report a different action taxonomy and generally leave these at 0 (read &#x60;actions&#x60; for those). At ad-set and campaign level each step is summed from its per-ad values.
 * @package     Zernio
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AdFunnelCountsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AdFunnelCounts"
     */
    public function testAdFunnelCounts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "landing_page_views"
     */
    public function testPropertyLandingPageViews()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "content_views"
     */
    public function testPropertyContentViews()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "searches"
     */
    public function testPropertySearches()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "wishlist_adds"
     */
    public function testPropertyWishlistAdds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cart_adds"
     */
    public function testPropertyCartAdds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "checkouts_initiated"
     */
    public function testPropertyCheckoutsInitiated()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payment_info_adds"
     */
    public function testPropertyPaymentInfoAdds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "purchases"
     */
    public function testPropertyPurchases()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "leads"
     */
    public function testPropertyLeads()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "registrations_completed"
     */
    public function testPropertyRegistrationsCompleted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "app_installs"
     */
    public function testPropertyAppInstalls()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "messaging_conversations_started"
     */
    public function testPropertyMessagingConversationsStarted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "messaging_first_replies"
     */
    public function testPropertyMessagingFirstReplies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
