<?php
/**
 * AnalyticsDeltaEntryMetricsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zernio\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AnalyticsDeltaEntryMetricsTest Class Doc Comment
 *
 * @category    Class
 * @description Metrics a platform does not report are 0, not absent.
 * @package     Zernio
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AnalyticsDeltaEntryMetricsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AnalyticsDeltaEntryMetrics"
     */
    public function testAnalyticsDeltaEntryMetrics()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "impressions"
     */
    public function testPropertyImpressions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reach"
     */
    public function testPropertyReach()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "likes"
     */
    public function testPropertyLikes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shares"
     */
    public function testPropertyShares()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "saves"
     */
    public function testPropertySaves()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sends"
     */
    public function testPropertySends()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "clicks"
     */
    public function testPropertyClicks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "views"
     */
    public function testPropertyViews()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "follows"
     */
    public function testPropertyFollows()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ig_reels_avg_watch_time"
     */
    public function testPropertyIgReelsAvgWatchTime()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ig_reels_video_view_total_time"
     */
    public function testPropertyIgReelsVideoViewTotalTime()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reposts"
     */
    public function testPropertyReposts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reels_skip_rate"
     */
    public function testPropertyReelsSkipRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
