<?php
/**
 * CheckInstagramHashtags200ResponseSummaryTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Late
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Late\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CheckInstagramHashtags200ResponseSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description CheckInstagramHashtags200ResponseSummary
 * @package     Late
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CheckInstagramHashtags200ResponseSummaryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CheckInstagramHashtags200ResponseSummary"
     */
    public function testCheckInstagramHashtags200ResponseSummary()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "banned"
     */
    public function testPropertyBanned()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "restricted"
     */
    public function testPropertyRestricted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "safe"
     */
    public function testPropertySafe()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
