<?php
/**
 * FollowerStatsResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Late
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Late\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FollowerStatsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description FollowerStatsResponse
 * @package     Late
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FollowerStatsResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FollowerStatsResponse"
     */
    public function testFollowerStatsResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "accounts"
     */
    public function testPropertyAccounts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "date_range"
     */
    public function testPropertyDateRange()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "aggregation"
     */
    public function testPropertyAggregation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
