<?php
/**
 * GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Late
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Late\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner
 * @package     Late
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner"
     */
    public function testGetGoogleBusinessLocationDetails200ResponseSpecialHoursSpecialHourPeriodsInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "open_time"
     */
    public function testPropertyOpenTime()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "close_time"
     */
    public function testPropertyCloseTime()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "closed"
     */
    public function testPropertyClosed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
