<?php
/**
 * GetInboxConversation200ResponseDataMetadataTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zernio\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetInboxConversation200ResponseDataMetadataTest Class Doc Comment
 *
 * @category    Class
 * @description Ad-click attribution for a conversation that started from a Meta ad. Absent when the conversation did not originate from an ad click.  Captured once, on the first inbound message after the click, and never overwritten. If the same person later clicks a different ad, the original values are kept. Meta only sends the referral on that first message.  This operation currently returns only the &#x60;meta_ad_*&#x60; family, which covers Instagram Click-to-Direct and Facebook Messenger Click-to-Message. WhatsApp Click-to-WhatsApp attribution (the &#x60;ctwa_*&#x60; keys, where the ad ID is &#x60;ctwa_source_id&#x60;) is returned by &#x60;GET /v1/inbox/conversations&#x60; instead.  Every key is optional and only the keys Meta supplied are returned, so read defensively. Meta does not send a campaign or ad set ID, so none is exposed here. More keys may be added over time. Treat any key you do not recognise as an opaque string.  Key names differ from the &#x60;message.received&#x60; webhook on purpose. The webhook forwards Meta&#39;s referral verbatim (&#x60;ad_id&#x60;, &#x60;source&#x60;, &#x60;type&#x60;) while the stored conversation record uses the prefixed names below. Renaming either side would break existing integrations, so both spellings are kept.
 * @package     Zernio
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetInboxConversation200ResponseDataMetadataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetInboxConversation200ResponseDataMetadata"
     */
    public function testGetInboxConversation200ResponseDataMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_id"
     */
    public function testPropertyMetaAdId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_source"
     */
    public function testPropertyMetaAdSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_type"
     */
    public function testPropertyMetaAdType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_ref"
     */
    public function testPropertyMetaAdRef()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_title"
     */
    public function testPropertyMetaAdTitle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_photo_url"
     */
    public function testPropertyMetaAdPhotoUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_video_url"
     */
    public function testPropertyMetaAdVideoUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_post_id"
     */
    public function testPropertyMetaAdPostId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_product_id"
     */
    public function testPropertyMetaAdProductId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_flow_id"
     */
    public function testPropertyMetaAdFlowId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_captured_at"
     */
    public function testPropertyMetaAdCapturedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
