<?php
/**
 * LinkedInPlatformDataPollTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zernio\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * LinkedInPlatformDataPollTest Class Doc Comment
 *
 * @category    Class
 * @description Create a LinkedIn poll with this post. Cannot be combined with media or reshareUrl. Polls cannot be edited after publishing on LinkedIn, and API-created polls are non-sponsored only (they cannot be promoted as ads).
 * @package     Zernio
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LinkedInPlatformDataPollTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LinkedInPlatformDataPoll"
     */
    public function testLinkedInPlatformDataPoll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "question"
     */
    public function testPropertyQuestion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
