<?php
/**
 * ListInboxConversations200ResponseDataInnerMetadataTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zernio\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ListInboxConversations200ResponseDataInnerMetadataTest Class Doc Comment
 *
 * @category    Class
 * @description Ad-click attribution for a conversation that started from a Meta ad. Absent when the conversation did not originate from an ad click.  Captured from the referral Meta attaches to the first inbound message after the click, which is the only message that carries it. If the same person later clicks a different ad, the original values are kept, so the first ad wins. One exception on WhatsApp: when Meta omits &#x60;ctwa_clid&#x60; from that referral, a later Meta automatic event can supply it and refresh &#x60;ctwa_captured_at&#x60;, so treat &#x60;ctwa_captured_at&#x60; as the time Zernio stored the value, not the time of the click.  Two families of keys, one per surface. They never appear together:    - &#x60;ctwa_*&#x60; is WhatsApp Click-to-WhatsApp. The ad ID is     &#x60;ctwa_source_id&#x60;. There is no &#x60;meta_ad_id&#x60; on WhatsApp.   - &#x60;meta_ad_*&#x60; is Instagram Click-to-Direct and Facebook Messenger     Click-to-Message. The ad ID is &#x60;meta_ad_id&#x60;. &#x60;ctwa_clid&#x60; never     appears on these platforms.  Every key is optional and only the keys Meta supplied are returned, so read defensively. Meta does not send a campaign or ad set ID, so none is exposed here. More keys may be added over time. Treat any key you do not recognise as an opaque string.  Key names differ from the &#x60;message.received&#x60; webhook on purpose. The webhook forwards Meta&#39;s referral verbatim (&#x60;ad_id&#x60;, &#x60;source&#x60;, &#x60;type&#x60;) while the stored conversation record uses the prefixed names below. Renaming either side would break existing integrations, so both spellings are kept.
 * @package     Zernio
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ListInboxConversations200ResponseDataInnerMetadataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListInboxConversations200ResponseDataInnerMetadata"
     */
    public function testListInboxConversations200ResponseDataInnerMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ctwa_clid"
     */
    public function testPropertyCtwaClid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ctwa_source_id"
     */
    public function testPropertyCtwaSourceId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ctwa_source_type"
     */
    public function testPropertyCtwaSourceType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ctwa_source_url"
     */
    public function testPropertyCtwaSourceUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ctwa_headline"
     */
    public function testPropertyCtwaHeadline()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ctwa_captured_at"
     */
    public function testPropertyCtwaCapturedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_id"
     */
    public function testPropertyMetaAdId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_source"
     */
    public function testPropertyMetaAdSource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_type"
     */
    public function testPropertyMetaAdType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_ref"
     */
    public function testPropertyMetaAdRef()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_title"
     */
    public function testPropertyMetaAdTitle()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_photo_url"
     */
    public function testPropertyMetaAdPhotoUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_video_url"
     */
    public function testPropertyMetaAdVideoUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_post_id"
     */
    public function testPropertyMetaAdPostId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_product_id"
     */
    public function testPropertyMetaAdProductId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_flow_id"
     */
    public function testPropertyMetaAdFlowId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meta_ad_captured_at"
     */
    public function testPropertyMetaAdCapturedAt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
