<?php
/**
 * ListLocalServicesLeads200ResponseDataInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zernio\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ListLocalServicesLeads200ResponseDataInnerTest Class Doc Comment
 *
 * @category    Class
 * @description ListLocalServicesLeads200ResponseDataInner
 * @package     Zernio
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ListLocalServicesLeads200ResponseDataInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListLocalServicesLeads200ResponseDataInner"
     */
    public function testListLocalServicesLeads200ResponseDataInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lead_type"
     */
    public function testPropertyLeadType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "service_id"
     */
    public function testPropertyServiceId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "created_time"
     */
    public function testPropertyCreatedTime()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "charged"
     */
    public function testPropertyCharged()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "credit_state"
     */
    public function testPropertyCreditState()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "credit_state_last_update"
     */
    public function testPropertyCreditStateLastUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
