<?php
/**
 * MediaItemTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Late
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Late\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MediaItemTest Class Doc Comment
 *
 * @category    Class
 * @description Media referenced in posts. URLs must be publicly reachable over HTTPS by the destination platforms. When using third‑party storage, ensure signed links remain valid until upload completes.  **Uploading Media:** Use &#x60;POST /v1/media/presign&#x60; to get a presigned URL, then upload your file directly to cloud storage. Supports files up to 5GB. See the &#x60;/v1/media/presign&#x60; endpoint documentation for details.  **Automatic Media Compression:** Late automatically compresses media that exceeds platform limits, so you don&#39;t need to worry about file size restrictions. Compression happens server-side during publishing.  **Image compression by platform:** - Twitter/X: &gt;5 MB - Instagram: &gt;8 MB - Threads: &gt;8 MB - Facebook: &gt;10 MB - LinkedIn: &gt;8 MB - TikTok: &gt;20 MB - Pinterest: &gt;32 MB - Reddit: &gt;20 MB - Snapchat: &gt;20 MB - Telegram: &gt;10 MB - Bluesky: &gt;1 MB - YouTube (thumbnails): &gt;2 MB - Google Business: &gt;5 MB  **Video compression by platform:** - Twitter/X: &gt;512 MB - Instagram Stories: &gt;100 MB - Instagram Reels: &gt;300 MB - Facebook: &gt;4 GB - LinkedIn: &gt;5 GB - TikTok: &gt;4 GB - Pinterest: &gt;2 GB - Snapchat: &gt;500 MB - Telegram: &gt;50 MB  Note: Videos larger than 200 MB may not be compressed due to server timeout constraints. For best results, compress very large videos before uploading.
 * @package     Late
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MediaItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MediaItem"
     */
    public function testMediaItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "filename"
     */
    public function testPropertyFilename()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "mime_type"
     */
    public function testPropertyMimeType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "thumbnail"
     */
    public function testPropertyThumbnail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "instagram_thumbnail"
     */
    public function testPropertyInstagramThumbnail()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tiktok_processed"
     */
    public function testPropertyTiktokProcessed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
