<?php
/**
 * ThreadsPlatformDataTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Late
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Late\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ThreadsPlatformDataTest Class Doc Comment
 *
 * @category    Class
 * @description Constraints: - Carousel posts support up to 10 images (no videos in carousels). - Single posts support one image or one video. - Videos must be H.264/AAC MP4 format, max 5 minutes duration. - Images must be JPEG or PNG, max 8 MB each. - threadItems creates a reply chain (Threads equivalent of Twitter threads).
 * @package     Late
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ThreadsPlatformDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ThreadsPlatformData"
     */
    public function testThreadsPlatformData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "thread_items"
     */
    public function testPropertyThreadItems()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
