<?php
/**
 * TikTokPlatformDataTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Late
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Late\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TikTokPlatformDataTest Class Doc Comment
 *
 * @category    Class
 * @description TikTok platform-specific settings for video/photo posting.  **Constraints:** - Photo carousels support up to 35 images. - **Title length limits**:   - Videos: up to 2200 chars (full content used as title)   - Photos: content is automatically truncated to 90 chars for title (hashtags/URLs stripped). Use &#39;description&#39; field for longer text (up to 4000 chars). - privacyLevel must be chosen from creator_info.privacy_level_options (no defaulting). - allowDuet and allowStitch required for videos; allowComment for all. - contentPreviewConfirmed and expressConsentGiven must be true before posting.  **Note:** Both camelCase and snake_case field names are accepted for backwards compatibility. The nested &#x60;tiktokSettings&#x60; object format is also still supported but deprecated.
 * @package     Late
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TikTokPlatformDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TikTokPlatformData"
     */
    public function testTikTokPlatformData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "draft"
     */
    public function testPropertyDraft()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "privacy_level"
     */
    public function testPropertyPrivacyLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "allow_comment"
     */
    public function testPropertyAllowComment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "allow_duet"
     */
    public function testPropertyAllowDuet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "allow_stitch"
     */
    public function testPropertyAllowStitch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "commercial_content_type"
     */
    public function testPropertyCommercialContentType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "brand_partner_promote"
     */
    public function testPropertyBrandPartnerPromote()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_brand_organic_post"
     */
    public function testPropertyIsBrandOrganicPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "content_preview_confirmed"
     */
    public function testPropertyContentPreviewConfirmed()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "express_consent_given"
     */
    public function testPropertyExpressConsentGiven()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "media_type"
     */
    public function testPropertyMediaType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "video_cover_timestamp_ms"
     */
    public function testPropertyVideoCoverTimestampMs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "photo_cover_index"
     */
    public function testPropertyPhotoCoverIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "auto_add_music"
     */
    public function testPropertyAutoAddMusic()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "video_made_with_ai"
     */
    public function testPropertyVideoMadeWithAi()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
