<?php
/**
 * ValueRuleSetTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zernio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api
 *
 * The version of the OpenAPI document: 1.0.4
 * Contact: support@zernio.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zernio\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ValueRuleSetTest Class Doc Comment
 *
 * @category    Class
 * @description A named set of bid-adjustment rules on an ad account. Attach it to an ad set with &#x60;valueRuleSetId&#x60;. Limits: 6 sets per ad account, 10 rules per set, 4 criteria per rule.
 * @package     Zernio
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ValueRuleSetTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ValueRuleSet"
     */
    public function testValueRuleSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rules"
     */
    public function testPropertyRules()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
