<?php
/**
 * GMBLocationDetailsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Late
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Late\Test\Api;

use \Late\Configuration;
use \Late\ApiException;
use \Late\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GMBLocationDetailsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Late
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GMBLocationDetailsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getGoogleBusinessLocationDetails
     *
     * Get Google Business Profile location details.
     *
     */
    public function testGetGoogleBusinessLocationDetails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateGoogleBusinessLocationDetails
     *
     * Update Google Business Profile location details.
     *
     */
    public function testUpdateGoogleBusinessLocationDetails()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
