<?php
/**
 * ToolsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Late
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Late\Test\Api;

use \Late\Configuration;
use \Late\ApiException;
use \Late\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ToolsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Late
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ToolsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for checkInstagramHashtags
     *
     * Check Instagram hashtags for bans.
     *
     */
    public function testCheckInstagramHashtags()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadBlueskyMedia
     *
     * Download Bluesky video.
     *
     */
    public function testDownloadBlueskyMedia()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadFacebookVideo
     *
     * Download Facebook video.
     *
     */
    public function testDownloadFacebookVideo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadInstagramMedia
     *
     * Download Instagram reel or post.
     *
     */
    public function testDownloadInstagramMedia()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadLinkedInVideo
     *
     * Download LinkedIn video.
     *
     */
    public function testDownloadLinkedInVideo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadTikTokVideo
     *
     * Download TikTok video.
     *
     */
    public function testDownloadTikTokVideo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadTwitterMedia
     *
     * Download Twitter/X video.
     *
     */
    public function testDownloadTwitterMedia()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadYouTubeVideo
     *
     * Download YouTube video or audio.
     *
     */
    public function testDownloadYouTubeVideo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getYouTubeTranscript
     *
     * Get YouTube video transcript.
     *
     */
    public function testGetYouTubeTranscript()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
